"""M8 Impact Measurement — synthetic season data + the difference-in-
differences (DiD) model that estimates a product's causal effect on
wheat yield from it.

M7 (Application & Logging) doesn't exist yet, so there is no real
outcome data to run this against. Per CLAUDE.md's "What's real vs.
simulated": the *input data* here is synthetic, generated by this file,
with a known ground-truth effect baked in on purpose — that's explicitly
called out as an allowed simulation. The *model* is real: an OLS
regression with a used_product * period interaction term, run with
statsmodels, exactly per CLAUDE.md's tech-stack choice (not DoWhy/EconML
— too much setup for the timeline).

--------------------------------------------------------------------
KNOWN GROUND TRUTH (we generated the data, so we know this number)
--------------------------------------------------------------------
TRUE_EFFECT_PCT below is a made-up, documented constant: farmers who use
the product see a 12.0% yield bump in the "after" period, on top of
whatever else is going on (soil, weather, a general season-to-season
trend everyone gets regardless of treatment). Nothing else in this file
is allowed to know this number — the DiD model estimates it purely from
the simulated panel, the same way it would from real M7 outcome logs
later. tests/test_impact.py checks the model actually recovers something
close to it; that's the whole point of building this against synthetic
data before real data exists.
"""
from dataclasses import dataclass
from typing import List

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

from app.services import data_foundation

# --- Ground truth for the synthetic generator (see module docstring) -------
TRUE_EFFECT_PCT = 12.0  # % yield uplift caused by the product, in the "after" period

# --- Grounded, documented assumptions for the generator ---------------------
# Punjab's average wheat yield is ~20.9 quintals/acre (state avg, 2023-24,
# PAU); medium-fertility soils run 18-20 q/acre, high-fertility 21-24 q/acre.
# 21.0 is a round baseline inside that real range — a documented assumption,
# not a measured figure for any specific farmer.
BASE_YIELD_QUINTALS_PER_ACRE = 21.0
TRUE_EFFECT_ABS_QUINTALS_PER_ACRE = TRUE_EFFECT_PCT / 100.0 * BASE_YIELD_QUINTALS_PER_ACRE

# A trend that lifts every farmer's yield between periods regardless of
# treatment (e.g. a generally better season) — this is *why* DiD is needed
# instead of a naive before/after comparison: it nets this common trend out.
COMMON_PERIOD_TREND_QUINTALS_PER_ACRE = 1.0

# Ordinal stand-in for water/nutrient retention by texture (sandy=lowest,
# clay loam=highest) — a loose assumption, not a measured soil-fertility
# index. Real soil texture strings come from M2's get_soil_type().
SOIL_TEXTURE_INDEX = {
    "sandy": 0.2,
    "sandy loam": 0.45,
    "loam": 0.7,
    "clay loam": 0.9,
}
SOIL_EFFECT_QUINTALS_PER_ACRE = 4.0  # yield swing across the soil index range
WEATHER_EFFECT_QUINTALS_PER_ACRE = 3.0  # yield swing across the weather index range

# Real wheat MSP for the 2025-26 marketing season (Rs 2,425/quintal) — used
# to convert the yield effect into a rupee figure. This makes roi_per_acre_inr
# gross additional revenue from the yield gain, not a fully netted ROI: we
# have no real per-acre product cost data to subtract (that's Syngenta
# pricing, not available yet), so this is deliberately conservative in what
# it claims to represent.
WHEAT_MSP_INR_PER_QUINTAL = 2425

N_FARMERS = 300
RANDOM_SEED = 42  # fixed so the synthetic panel — and the model fit on it — is reproducible

_DISTRICTS = [
    "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Sangrur",
    "Ferozepur", "Moga", "Fatehgarh Sahib", "Gurdaspur", "Hoshiarpur",
    "Kapurthala", "Mansa", "Muktsar", "Rupnagar", "SAS Nagar Mohali",
    "Faridkot", "Fazilka", "Barnala", "Tarn Taran", "Pathankot",
]


def _soil_index_for(district: str) -> float:
    soil_type = data_foundation.get_soil_type(district)
    return SOIL_TEXTURE_INDEX.get(soil_type, 0.6)


def generate_synthetic_season_panel(n_farmers: int = N_FARMERS, seed: int = RANDOM_SEED) -> pd.DataFrame:
    """One row per farmer per period (before/after) — the panel shape a
    real difference-in-differences analysis expects. Two rows per farmer,
    same farmer_id, differing only in `period` and what happened that season.
    """
    rng = np.random.default_rng(seed)

    farmer_ids = [f"sim-farmer-{i:04d}" for i in range(n_farmers)]
    districts = rng.choice(_DISTRICTS, size=n_farmers)
    used_product = rng.integers(0, 2, size=n_farmers)  # random treatment assignment
    # Time-invariant, unobserved field/farmer quality — DiD's differencing
    # cancels this out as long as it doesn't itself depend on treatment
    # (it doesn't here: draws are independent of used_product).
    farmer_fixed_effect = rng.normal(0.0, 2.0, size=n_farmers)

    rows: List[dict] = []
    for i in range(n_farmers):
        district = districts[i]
        soil_index = _soil_index_for(district)
        for period in (0, 1):
            weather_index = float(np.clip(rng.normal(0.6, 0.15), 0.1, 1.0))
            treatment_bump = (
                TRUE_EFFECT_ABS_QUINTALS_PER_ACRE if (used_product[i] == 1 and period == 1) else 0.0
            )
            noise = rng.normal(0.0, 1.0)

            yield_outcome = (
                BASE_YIELD_QUINTALS_PER_ACRE
                + COMMON_PERIOD_TREND_QUINTALS_PER_ACRE * period
                + SOIL_EFFECT_QUINTALS_PER_ACRE * soil_index
                + WEATHER_EFFECT_QUINTALS_PER_ACRE * weather_index
                + farmer_fixed_effect[i]
                + treatment_bump
                + noise
            )

            rows.append(
                {
                    "farmer_id": farmer_ids[i],
                    "district": district,
                    "soil_index": soil_index,
                    "weather_index": weather_index,
                    "used_product": int(used_product[i]),
                    "period": period,
                    "yield_outcome": yield_outcome,
                }
            )

    return pd.DataFrame(rows)


@dataclass
class DiDResult:
    estimated_effect_abs: float  # quintals/acre, from the used_product:period coefficient
    estimated_effect_pct: float  # as a % of BASE_YIELD_QUINTALS_PER_ACRE
    confidence_range_pct: List[float]  # 95% CI, same units as estimated_effect_pct
    n_observations: int


def fit_did_model(panel: pd.DataFrame) -> DiDResult:
    """OLS with a used_product * period interaction term, controlling for
    weather_index and soil_index — the interaction coefficient is the
    causal DiD estimate, per CLAUDE.md.
    """
    model = smf.ols(
        "yield_outcome ~ used_product * period + weather_index + soil_index",
        data=panel,
    ).fit()

    interaction_term = "used_product:period"
    effect_abs = model.params[interaction_term]
    ci_low, ci_high = model.conf_int(alpha=0.05).loc[interaction_term]

    to_pct = lambda q: round(q / BASE_YIELD_QUINTALS_PER_ACRE * 100.0, 1)

    return DiDResult(
        estimated_effect_abs=round(effect_abs, 3),
        estimated_effect_pct=to_pct(effect_abs),
        confidence_range_pct=sorted([to_pct(ci_low), to_pct(ci_high)]),
        n_observations=int(model.nobs),
    )


_cached_result: DiDResult | None = None


def get_or_fit_did_result() -> DiDResult:
    """The synthetic panel and its fit are deterministic (fixed seed), so
    there's no reason to regenerate/refit on every request — cache once
    per process, same lazy-build pattern as M4's retrieval index."""
    global _cached_result
    if _cached_result is None:
        panel = generate_synthetic_season_panel()
        _cached_result = fit_did_model(panel)
    return _cached_result
